### ISSUE TITLE
Sorry to ask

### ISSUE THREAD

**Issue by enjoybeta** [alberthdev/alberthdev-misc#1]
If possible, could you share the .lib files for static build of qt5.6? Because I just hate using command line, exhausting to set up environment.

**Comment by alberthdev** [comment]
Definitely - but I'm not sure if there's a good place to host the archives. Any ideas?

(There's a semi-public link that is out there, but it's heavily customized and stripped down, and I'm not sure if they care about bandwidth...)

**Comment by enjoybeta** [comment]
maybe google driver? I am not sure the size of the file will be ok?

**Comment by alberthdev** [comment]
@enjoybeta - Sorry for the delay in response - I decided to upload them to Mega instead! (I don't have much space in Google Drive, while Mega has way more space available - 50 GBs!)

https://mega.nz/#F!fRE3DRQD!OxJcmIciB4PKhQo-kU4-bg

This can also be found in the [wiki page](../wiki/Building-Qt-v5.6-Statically-on-Windows#binaries) as well under binaries.

Let me know if you need anything else!
